### PR TITLE
Added kWh to contrib/oregon_scientific.c and minor tweaks in src/rtl_433/pulse_demod.c

### PR DESCRIPTION
**Pull request by diepeterpan**
oregon_scientific.c changes were also merged into the PC version @ https://github.com/merbanan/rtl_433

### CODE REVIEW

**Comment by NorthernMan54** [comment]
@diepeterpan Are we good to go with this ? I ran the build for the last 24hours and it looks okay

**Comment by diepeterpan** [comment]
> @diepeterpan Are we good to go with this? I ran the build for the last 24 hours and it looks okay

So far so good, I mentioned to "_merbanan/rtl_433_" that I have a second device and I will verify the numbers, but that is another couple of days away before I can use that device.

**Comment by NorthernMan54** [comment]
Okay, will hold off on merging this until you complete testing.

**Comment by diepeterpan** [comment]
> Okay, will hold off on merging this until you complete testing.

I have done so much testing and googling the past day. My answer on kWh appears to be a consistent 12% lower, whether I measure for 1 hour or for 10 hours.  I will check with "_merbanan/rtl_433_" what he thinks on whether I just * 1.12 ?

**Comment by diepeterpan** [comment]
> > Okay, will hold off on merging this until you complete testing.
> 
> I have done so much testing and googling the past day. My answer on kWh appears to be a consistent 12% lower, whether I measure for 1 hour or for 10 hours. I will check with "_merbanan/rtl_433_" what he thinks on whether I just * 1.12 ?

I have for now added the additional 1.12 in the code.

**Comment by diepeterpan** [comment]
Replaced by https://github.com/NorthernMan54/rtl_433_ESP/pull/65

**Pull request closed without merging**
