### PR TITLE
Update of rtl_433 device decoders to rtl_433 Release 21.12

### PR DESCRIPTION
**Pull request by NorthernMan54**
Includes the following other updates:

1 - Workaround for cc1101 module going deaf after 24 hours, issue #16.
    - By default the workaround is enabled, define NO_DEAF_WORKAROUND to remove the workaround

2 - Improved process for updating from rtl_433 for GitHub, almost totally automated.
    - FYI - Their is a shell script in the tools subdirectory which does most of the heavy lifting required

3 - Updated device decoders to latest release of rtl_433
    - They are now in align with rtl_433 release 21.12

4 - Updated r_api.c to prioritize ook demodulators - feature from rtl_433

5 - Created contrib directory for other device decoders to be merged into code base as part of the rtl_433 update process

6 - Bump library version to 0.0.3

7 - Tuned signal receiver logic and now throw away the first received byte.  On testing this appears to dramatically reduce the number of unparsed signals.

8 - Fixed README feedback from @DigiH and updated the wording for 'PUBLISH_UNPARSED'.  Also removed serial logging of unparsed messages unless 'PUBLISH_UNPARSED' is set

9 - Added new DEFINITION to enable rtl_433 verbose mode for a single device decoder.  RTL_VERBOSE=##

### CODE REVIEW

**Comment by jtheuer** [comment]
Hi @NorthernMan54 thanks for your great work on this project. I was reading your implementation in `src/rtl_433/devices/tfa_30_3221.c`. I was wondering if you had any pointers how I could port this "back" to the twilight project. (I've seen you mentioned this on your Readme):

> Inspiration for this came from the ESPiLight effort. Kudos to puuu for this, and the awesome package.

So I was wondering if there is theoretically any easy to use compatibility between the parsing approach of both projects. Many thanks in advance.

**Comment by NorthernMan54** [comment]
Well I’m using the device decoder directly from rtl_433 aka https://github.com/merbanan/rtl_433 and also carried over some of the logic surrounding the device decoders with it wired to my own signal receiver code.

I’m not familiar with the twilight project can you supply a link?

**Comment by jtheuer** [comment]
Apologize for the lack of context here. I was referring to this file from your project: https://github.com/NorthernMan54/rtl_433_ESP/blob/master/src/rtl_433/devices/tfa_30_3221.c

And I was wondering if / to what extend your work bases on this project https://github.com/puuu/ESPiLight. It uses [internally the drivers from pilight](https://github.com/puuu/ESPiLight?utm_source=platformio&utm_medium=piohome#new-protocols). Here is one example for a similar (but incompatible) tfa reader: https://github.com/pilight/pilight/blob/ee7231263340dc08b97edf5dc184ee67d907b430/libs/pilight/protocols/433.92/tfa30.c

If you see a change to back port it, any help would be really appreciated. (To me both files look conceptually totally different, unfortunately)

**Comment by NorthernMan54** [comment]
I think you read too much into my comment about the pilight inspiration.  This project code is largely based on [rtl_433](https://github.com/merbanan/rtl_433) and not pilight.  With pilight it was just the concept of reusing device decoders from other librarys I borrowed for inspiration.  So I will not be back porting this to pilight, as it did not originate from there.

**Pull request merged**
