### PR TITLE
Signal file for Fineoffset WH0530 device

### PR DESCRIPTION
**Pull request by AusGunno**
Initial data capture for WH0530
Needs more work as decoding is not yet reliable, but a good start.

### CODE REVIEW

**Comment by NorthernMan54** [comment]
Tks

I had put them there as placeholder while working thru the initial port

**Comment by NorthernMan54** [comment]
@AusGunno On thing I found when looking at the results of my Philips temperature sensor, was that the ESP version and rtl_433 where picking up the same issues with decode.  Hence an issue with the signal decode logic.

**Comment by AusGunno** [comment]
@NorthernMan54 Thanks mate. I have been looking at this with an SDR_RTL dongle and the protocol seems to be working ok. Using the CC1100 config as is, I was getting about 15% hit rate. Looking at the data the ESP32/CC1101 seems to have an issue with the first pulse - its often significantly less than the nominal pulse width for this device so is not being recognised. I changed the code for the short pulse processing for the first pulse only to accept 50% of the one PW. This improved the hit rate to over 25%. Im thinking that the CC1100 gains are an issue. Looking at the CC1100 settings for Async mode it seems that the default gains may not be optimized for OOK/ASK. Default are:
SpiWriteReg(CC1101_AGCCTRL2, 0xC7);
    SpiWriteReg(CC1101_AGCCTRL1, 0x00);
    SpiWriteReg(CC1101_AGCCTRL0, 0xB2);
Whereas RF Studio for OOK 5k data rate recommends:
    SpiWriteReg(CC1101_AGCCTRL2, 0x03);
    SpiWriteReg(CC1101_AGCCTRL1, 0x00);
    SpiWriteReg(CC1101_AGCCTRL0, 0x91);
Sadly these did not work for me. Best I can get is:
    SpiWriteReg(CC1101_AGCCTRL2, 0xC3);
    SpiWriteReg(CC1101_AGCCTRL1, 0x00);
    SpiWriteReg(CC1101_AGCCTRL0, 0x92);
AGCCTRL2 is the main one controlling overall gains. Still need to play some more with this.

Really keen to play with FSK demods - as I have a WH51 Soil Moisture sensor. How much effort do you think it will be to get the FSK protocols working. Still working my way through the rtl_433 code to understand it so any thoughts you may have on this ?

**Comment by AusGunno** [comment]
@NorthernMan54 - my use for this software will be very specific protocols that have already been decoded using RTL_SDR. As such I hope to just optimise the ESP32 and CC1101 config for the given protocols.
From what I can see the FSK decoder uses that same lower level decoders that the ASK decoder uses. The smarts then is in configuring the CC1101 to demodulate the received signal correctly.

Let me know if you think this will work for FSK:
rtl_433_ESP changes to support FSK registered decoders and relevant setup (initReceiver - add in modulation mode) etc
CC1101 change configuration modulation - 2-FSK (Modulation = 0) - changes to call setmodulation from init
CC1101 change config of relevant registers to support specific decoder based on RTL_SDR parameters using RF Studio. 

End game - assuming the CC1101 can demodulate the FSK waveform and output the async data stream - rtl_433_ESP with a few simple changes should be able to decode it in the same way it does ASK/OOK?
Cheers

**Comment by NorthernMan54** [comment]
When I completed the original port I had descoped the fsk devices as I had no method of testing.  I could in a beta branch re-enable them and hopefully you can test them for me.

give me a day to set this up

**Comment by NorthernMan54** [comment]
Okay the FSK branch has the FSK Encoders copied into the code base and they are compiling but still needs more effort before we should be able to test.  Next step would be wiring them into the receive flow, and invoke them when using FSK modulation and the existing OOK decoders when using ASK modulation.  I also need to look at how the current receiver code handles the signal to see if changes are needed for FSK signals.

I also added a new function setModulation to allow for switching the current receive modulation.

Question, would you be aware of a package I could upload to one of my ESP32/CC1101 devices to simulate a FSK device?  That way I could test this out

**Comment by AusGunno** [comment]
Thanks,

 

Sorry no not aware of any simulator.

 

Will have a play with the code.

**Comment by NorthernMan54** [comment]
Would it be possible to modify this example to send a signal simulating your device ?  Then I can use it to do some testing.

https://github.com/LSatan/SmartRC-CC1101-Driver-Lib/blob/master/examples/CC1101%20default%20examples/Old_Method_with_GDO/cc1101_Transmitt_Serial_advanced/cc1101_Transmitt_Serial_advanced.ino

**Comment by NorthernMan54** [comment]
Moved to #5

**Pull request merged**
