### PR TITLE
Add pre-commit setup

### PR DESCRIPTION
**Pull request by mdeweerd**
I propose the addition of a pre-commit setup which helps to format documentation and code, and make some static code checks upon commit.
That helps improve code quality.

I've adjusted some markdown files so that verbatim lines will not suffer from markdown file formatting.

```shell
pip install pre-commit
# Run specific hooks
pre-commit run -a codespell
pre-commit run -a cpplint
# Run all hooks (that would run on commit)
pre-commit run -a
# To run on every commit
pre-commit install
```

I've disabled most notifications.

### CODE REVIEW

**Comment by NorthernMan54** [comment]
Sorry am not familiar with pre-commit, is it significantly different than the existing GitHub actions ?

**Comment by mdeweerd** [comment]
pre-commit is a tool that helps you run other tools locally upon commit.
It helps you to avoid committing code that would fail in the workflow, still needs formatting or other code corrections.

It is similar to a workflow because it can run some of the same tools, and in certain projects pre-commit is also run in the workflow (on selected pre-commit hooks).

In the workflow you generally do not allow changes to your code, while locally with pre-commit you will generally allow them.  So when you use pre-commit, you normally do more locally.

pre-commit does more here because of the other checks.  for instance, it also helps check spelling:

```plaintext
src/rtl_433_ESP.h:89: interupt ==> interrupt
src/rtl_433_ESP.h:226: formated ==> formatted
src/rtl_433_ESP.h:255: formated ==> formatted
src/rtl_433_ESP.h:261: minumum ==> minimum
src/rtl_433_ESP.h:283: interupt ==> interrupt
src/rtl_433_ESP.h:411: avaiable ==> available
``

**Comment by NorthernMan54** [comment]
@mdeweerd I just did a commit from GitHub Desktop from this pull request, and didn't see anything ?

**Comment by mdeweerd** [comment]
I am not familiar with Github Desktop.  It seems that it is able to run pre-commit (https://github.com/desktop/desktop/issues/13112).  So there must be a way to run "pre-commit install" to add the hooks to the git clone.

**Comment by NorthernMan54** [comment]
Tks

**Pull request merged**
