### PR TITLE
Add device VEVOR 7in1

### PR DESCRIPTION
**Pull request by toxic0berliner**
## :recycle: Current situation

My Device VEVOR 7in1 is not recognized

## :bulb: Proposed solution

Add the device as it's supported by the latest rtl_433 lib

## :gear: Release Notes

add support for Vevor 7 in 1

## :heavy_plus_sign: Additional Information

I sadly do not own SDR and wasn't able to confirm myself my Vevor 7in1 device is working properly with RTL_433 but it was added in august this year through https://github.com/merbanan/rtl_433/commit/d1e1db9e568d9631cd4e2c1cca5de4b353092018 and people in the discussions seem to say it works.
The device file was taken directly from the rtl_433 repo here https://github.com/merbanan/rtl_433/blob/master/src/devices/vevor_7in1.c

### Testing
no tests added or removed

### Reviewer Nudging

For some reason I was not able to build a working openmqtt build, I am using https://docs.openmqttgateway.com/upload/gitpod.html to build and changed only platformio.ini file on line 153 to use my fork of this : `rtl_433_ESP = https://github.com/toxic0berliner/rtl_433_ESP.git#main`

The only way I have to test is to actually build and install on my [https://www.lilygo.cc/products/lora3?variant=42476923879605](LoRa32 V2.1_1.6) device, and so far it keeps rebooting and somehow the url is http and not https...

So I probably need help in actually adding this device properly to this repo.

Any help is appreciated I'll do my best to build&test it.

### CODE REVIEW

**Comment by toxic0berliner** [comment]
As you can see it took me quite a while but I have now managed to build a firmware and upload it to my lilygo device.
Sadly it doesn't seem to pickup the signals at all.
I will be squashing these commits to get rid of my crazy attempts, but I still would appreciate if anyone can help me debug why it's not picking any signal.

**Comment by NorthernMan54** [comment]
A couple of comments

1 - The number of commits isn't really an issue, as I would just squash and merge it.

2 - I can't really tell what you changed, as the PR says 220 files changed.  It is impossible to review.  Pls resubmit with just the changed files.

When working with a new device, or a non working device I follow try do this

1 - Confirm that the board it actually receiving a signal from the device - `RAW_SIGNAL_DEBUG`

I watch this output to ensure that the signal from the device is actually being received.  As these boards have range issues etc, it is best to confirm a signal is being received.  Then once I have that, then I look at the signal decoders.

**Comment by toxic0berliner** [comment]
I understand this is too many files for a PR by an unknown and unskilled guy like me, but it seems to me this repo copies and edits manually many files from the rtl_433 project, and over the last year they have made significant changes over there and added my device decoder only very recently.
I'm also unsure as to which scripts in the tools subfolder are to be used, in which order, and if I maybe missed something in the manually edited/commented c files...
Even if you leave adding the vevor device to me, would it be possible for you to "upgrade" to the latest rtl_433 ? You'll see every decoder seems to be modified, widely used functions like data_append have been replaced by type safe functions, ...  I don't think I will be able to add my decoder unless the codebase is refreshed...

I will enable the debug flag you kindly pointed to me and verify if I do get a signal, I have only a few meters and a single wall but I 'll be happy to know for sure.

Thanks in advance for any help, I will try it differently and submit a new PR, hopefully after someone migrate this to the latest rtl_433 code 😉

**Comment by mpietrusa** [comment]
Hello @toxic0berliner 
I just wanted to share, I appreciate your hard work to trying to add vevor 7 in 1 to rtl_433_esp. 
As you, I am onwer of this device and I am looking forward when lastest changes form rtl_433_esp will be included in this project.

**Comment by NorthernMan54** [comment]
I just pulled in a refresh #161

**Comment by toxic0berliner** [comment]
I have rebuild openMQTT changing the lib as follows in platformio.ini :
  rtl_433_ESP = https://github.com/NorthernMan54/rtl_433_ESP.git#v0.4.0
then used my own webserver to make the firmware.bin available and use OTA update.
sadly either my board is broken or it doesn't work as I'm not getting any `RTL_433toMQTT` topic, I do get the RSSI, the uptime and such... Seems my board is recieving nothing or unable to decode any of it.
It is placed right next to the base station of the weatherstation that is indeed recievieng the sensor data properly so range should not be the issue here.

**Pull request closed without merging**
