### PR TITLE
Adding support for Oregon-CM160 device and enabling OOK_PULSE_MANCHESTER_ZEROBIT using ESP32 DevKit V1 and external SX1278

### PR DESCRIPTION
**Pull request by diepeterpan**
Thank you for the assistance, tested for 8 hours straight without any problems, support for Oregon-CM160 device and enabling OOK_PULSE_MANCHESTER_ZEROBIT using ESP32 DOIT DevKit V1 and external SX1278 module (Ai-Thinker Ra-01).

### CODE REVIEW

**Comment by diepeterpan** [comment]
Also did a OpenMQTTGateway build pointing to my fork and voila!

image

**Comment by NorthernMan54** [comment]
I can release this later today, could you also include a copy of oregon_scientific.c in the contrib directory.  I don’t want to lose a copy of your changes, with further updates from rtl_433.

**Comment by NorthernMan54** [comment]
Also, did you see this

https://github.com/NorthernMan54/rtl_433_ESP/blob/1b689e17c3824eb4f6a4b3e8eed4b04f198b0af9/src/rtl_433_ESP.h#L73

pin mapping based on board type?  Simplifies platformio config

**Comment by diepeterpan** [comment]
I did see that, but had two problems:

1) I don’t know how to test for the specific board I could not find a (defined) value in the PlatformIO board file to identify it, maybe just me being dumb, any help appreciated.
2) The ESP32 and Ai-Thinker Ra01 SX1278 are two separate items and you can wire it differently, but if 1) is resolved I can add my selection :-)

**Comment by NorthernMan54** [comment]
Sorry I had assumed that it was a single board like the lilygo and heltec with the esp32 and sx127x on the same unit.

just ignore this then

**Comment by NorthernMan54** [comment]
Tks very much for this addition, it will be released later today

**Pull request merged**
